#!/usr/bin/env python

Import("env")

env.scene_sources = []

# Godot source files
if env.add_source_files(env.scene_sources, "*.cpp") == False:
    SConscript("audio/SCsub")
    SConscript("debugger/SCsub")

# Chain load SCsubs
SConscript("main/SCsub")
SConscript("gui/SCsub")
SConscript("3d/SCsub")
SConscript("2d/SCsub")
SConscript("animation/SCsub")
SConscript("resources/SCsub")

# Build it all as a library
lib = env.add_library("scene", env.scene_sources)
env.Prepend(LIBS=[lib])
